<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowLeft, Building2, Check, Mail, Phone, UserRound } from 'lucide-vue-next'

type Account={company?:string;fullName?:string;email?:string;phone?:string;password?:string}
const router=useRouter(),saved=ref(false),error=ref('')
const account:Account=JSON.parse(localStorage.getItem('qr-menu-account')||'{}')
const names=(account.fullName||localStorage.getItem('qr-menu-profile-name')||'').trim().split(/\s+/)
const firstName=ref(names[0]||''),lastName=ref(names.slice(1).join(' ')),company=ref(account.company||''),email=ref(account.email||''),phone=ref(account.phone||'')
function save(){if(!firstName.value.trim()||!lastName.value.trim()){error.value='Lütfen ad ve soyadınızı yazın.';return}const fullName=`${firstName.value.trim()} ${lastName.value.trim()}`;localStorage.setItem('qr-menu-account',JSON.stringify({...account,company:company.value.trim(),fullName,email:email.value.trim(),phone:phone.value.trim()}));localStorage.setItem('qr-menu-profile-name',fullName);window.dispatchEvent(new Event('qr-menu-profile-updated'));error.value='';saved.value=true;setTimeout(()=>saved.value=false,1800)}
</script>

<template><div class="account-page"><header><div><span>HESAP AYARLARI</span><h2>Profil bilgileriniz</h2><p>Kayıt sırasında verdiğiniz bilgileri görüntüleyin ve güncelleyin.</p></div><button @click="router.push('/admin')"><ArrowLeft :size="16"/> Panele dön</button></header><section class="account-card"><div class="profile-summary"><div class="profile-avatar">{{firstName.slice(0,1).toUpperCase()}}{{lastName.slice(0,1).toUpperCase()}}</div><div><h3>{{firstName||'Ad'}} {{lastName||'Soyad'}}</h3><p>{{email||'E-posta bilgisi yok'}}</p></div><span>İşletme hesabı</span></div><form @submit.prevent="save"><label class="wide"><span><Building2 :size="15"/>Firma ticari ünvanı</span><input v-model="company" placeholder="Firma veya restoran adı"/></label><div class="form-grid"><label><span><UserRound :size="15"/>Ad</span><input v-model="firstName" placeholder="Adınız" required/></label><label><span><UserRound :size="15"/>Soyad</span><input v-model="lastName" placeholder="Soyadınız" required/></label></div><div class="form-grid"><label><span><Mail :size="15"/>E-posta</span><input v-model="email" type="email" placeholder="ornek@restoran.com"/></label><label><span><Phone :size="15"/>Cep telefonu</span><input v-model="phone" type="tel" placeholder="05XX XXX XX XX"/></label></div><p v-if="error" class="form-error">{{error}}</p><div class="form-actions"><small>Değişiklikler hesabınıza otomatik kaydedilir.</small><button type="submit"><Check :size="17"/>{{saved?'Kaydedildi':'Bilgileri kaydet'}}</button></div></form></section></div></template>

<style scoped>
.account-page{max-width:900px;margin:auto}.account-page>header{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:24px}.account-page header>div>span{font-size:10px;letter-spacing:1.4px;color:var(--orange);font-weight:800}.account-page h2{font-size:31px;letter-spacing:-1px;margin:7px 0}.account-page header p{font-size:13px;color:var(--muted);margin:0}.account-page header>button{height:42px;border:1px solid var(--line);border-radius:10px;background:#fff;padding:0 14px;display:flex;align-items:center;gap:7px;font-size:12px;font-weight:700;cursor:pointer}.account-card{background:#fff;border:1px solid var(--line);border-radius:17px;box-shadow:0 7px 27px #2025220d;overflow:hidden}.profile-summary{min-height:125px;padding:25px 28px;display:flex;align-items:center;gap:15px;background:linear-gradient(125deg,#202a24,#2f3b34);color:#fff}.profile-avatar{width:62px;height:62px;border-radius:17px;background:linear-gradient(145deg,#f28a54,#d85c27);display:grid;place-items:center;font-size:18px;font-weight:800}.profile-summary h3{font-size:18px;margin:0 0 5px}.profile-summary p{font-size:11px;color:#aeb8b1;margin:0}.profile-summary>span{margin-left:auto;border:1px solid #ffffff20;background:#ffffff0c;border-radius:20px;padding:7px 10px;font-size:9px}.account-card form{padding:28px}.account-card label{display:block}.account-card label>span{display:flex;align-items:center;gap:6px;font-size:11px;font-weight:700;color:#515a54;margin-bottom:8px}.account-card label svg{color:var(--orange)}.account-card input{height:45px;width:100%;border:1px solid #dde1dd;border-radius:10px;padding:0 13px;outline:none;background:#fbfcfa;font-size:13px}.account-card input:focus{border-color:var(--orange);box-shadow:0 0 0 3px #e86e3515;background:#fff}.wide{margin-bottom:18px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:18px}.form-error{font-size:11px;color:#cc4c42}.form-actions{display:flex;align-items:center;justify-content:space-between;border-top:1px solid var(--line);padding-top:20px;margin-top:7px}.form-actions small{font-size:9px;color:#969e98}.form-actions button{height:43px;border:0;border-radius:10px;background:#202522;color:#fff;padding:0 17px;display:flex;align-items:center;gap:8px;font-size:11px;font-weight:800;cursor:pointer}.form-actions button:hover{background:var(--orange)}@media(max-width:650px){.account-page>header{align-items:stretch;flex-direction:column}.account-page header>button{justify-content:center}.profile-summary>span{display:none}.account-card form{padding:20px}.form-grid{grid-template-columns:1fr}.form-actions{align-items:stretch;flex-direction:column;gap:13px}.form-actions button{justify-content:center}}
</style>
