<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Check, ImagePlus, PackageOpen, Pencil, Plus, Search, Snowflake, Trash2, X } from 'lucide-vue-next'
import { clearStocksRemote, createStockRemote, fetchStocks, getStocks, removeStockRemote, updateStockRemote } from '../services/stocks'
import type { Stock } from '../types'
import '../photo.css'
const stocks=ref(getStocks()),search=ref(''),modal=ref(false),editing=ref<Stock|null>(null),name=ref(''),price=ref<number|null>(null),image=ref(''),category=ref('Ana Yemekler')
const categories=['Ana Yemekler','Gün Menüleri','Kebaplar','Hamur İşleri','Tostlar','Kahvaltı','Çorbalar','Başlangıçlar','Atıştırmalıklar','Tatlılar','İçecekler']
const filtered=computed(()=>stocks.value.filter(s=>s.name.toLocaleLowerCase('tr').includes(search.value.toLocaleLowerCase('tr'))))
const activeCount=computed(()=>stocks.value.filter(s=>s.status==='active').length)
const money=(v:number)=>`${v.toLocaleString('tr-TR')} ₺`
onMounted(async()=>{try{stocks.value=await fetchStocks()}catch(e){console.error(e)}})
function openModal(s?:Stock){editing.value=s??null;name.value=s?.name??'';price.value=s?.price??null;image.value=s?.image??'';category.value=s?.category??'Ana Yemekler';modal.value=true}
function selectImage(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f||f.size>3*1024*1024)return;const r=new FileReader();r.onload=()=>image.value=String(r.result);r.readAsDataURL(f)}
async function save(){if(!name.value.trim()||!price.value)return;try{if(editing.value)await updateStockRemote({...editing.value,name:name.value.trim(),price:price.value,category:category.value,image:image.value||undefined});else await createStockRemote(name.value.trim(),price.value,category.value,image.value||undefined);stocks.value=await fetchStocks();modal.value=false}catch(e){alert(e instanceof Error?e.message:'Ürün kaydedilemedi.')}}
async function remove(id:number){if(confirm('Bu ürünü kalıcı olarak silmek istediğinize emin misiniz?')){await removeStockRemote(id);stocks.value=await fetchStocks()}}
async function removeAll(){if(stocks.value.length&&confirm(`${stocks.value.length} ürünün tamamı kalıcı olarak silinecek. Devam etmek istiyor musunuz?`)){await clearStocksRemote();stocks.value=[]}}
async function toggle(s:Stock){await updateStockRemote({...s,status:s.status==='active'?'frozen':'active'});stocks.value=await fetchStocks()}
</script>
<template>
<div class="inventory-page">
  <header class="inventory-head"><div><span class="eyebrow accent">ÜRÜN YÖNETİMİ</span><h2>Ürünler</h2><p>Menünüzdeki ürünleri, fiyatlarını ve yayın durumlarını tek yerden yönetin.</p></div><div class="head-actions"><button class="delete-all" :disabled="!stocks.length" @click="removeAll"><Trash2 :size="17"/> Tümünü sil</button><button class="primary" @click="openModal()"><Plus :size="18"/> Yeni ürün ekle</button></div></header>
  <section class="summary"><div><span>Toplam ürün</span><strong>{{stocks.length}}</strong></div><i/><div><span>Yayında</span><strong class="green">{{activeCount}}</strong></div><i/><div><span>Pasif</span><strong>{{stocks.length-activeCount}}</strong></div></section>
  <section class="inventory-panel">
    <div class="toolbar"><div class="search-box modern-search"><Search :size="18"/><input v-model="search" placeholder="Ürünlerde ara..."/><button v-if="search" @click="search=''" aria-label="Temizle"><X :size="15"/></button></div><span class="result-count">{{filtered.length}} ürün</span></div>
    <div v-if="filtered.length">
      <div class="list-head"><span>Ürün</span><span>Fiyat</span><span>Durum</span><span>İşlemler</span></div>
      <article v-for="stock in filtered" :key="stock.id" class="product-row">
        <div class="product-main"><div class="product-photo"><img v-if="stock.image" :src="stock.image" :alt="stock.name"/><PackageOpen v-else :size="25"/></div><div><strong>{{stock.name}}</strong><small>{{stock.category}}</small></div></div>
        <strong class="price">{{money(stock.price)}}</strong>
        <button :class="['switch-wrap',{off:stock.status!=='active'}]" @click="toggle(stock)"><span class="switch"><i/></span>{{stock.status==='active'?'Aktif':'Pasif'}}</button>
        <div class="actions"><button class="edit" @click="openModal(stock)"><Pencil :size="16"/><span>Düzenle</span></button><button class="freeze" @click="toggle(stock)"><Snowflake :size="16"/></button><button class="delete" @click="remove(stock.id)"><Trash2 :size="16"/></button></div>
      </article>
    </div>
    <div v-else class="empty-state"><span><PackageOpen :size="30"/></span><h3>Ürün bulunamadı</h3><p>Arama kelimenizi değiştirin veya yeni bir ürün ekleyin.</p></div>
  </section>
</div>
<div v-if="modal" class="modal-backdrop" @click.self="modal=false"><form class="modal product-modal" @submit.prevent="save"><button type="button" class="modal-close" @click="modal=false"><X :size="18"/></button><span class="modal-kicker">{{editing?'ÜRÜNÜ GÜNCELLE':'YENİ ÜRÜN'}}</span><h3>{{editing?'Ürün bilgilerini düzenle':'Menünüze ürün ekleyin'}}</h3><p>Temel bilgileri girin; ürünü dilediğiniz zaman güncelleyebilirsiniz.</p>
  <label>Ürün görseli<div class="photo-picker product-picker"><img v-if="image" :src="image" alt="Ürün önizlemesi"/><div v-else><ImagePlus :size="25"/><strong>Görsel yükleyin</strong><small>PNG, JPG veya WEBP · En fazla 3 MB</small></div><input type="file" accept="image/png,image/jpeg,image/webp" @change="selectImage"/></div></label>
  <div class="form-grid"><label>Ürün adı *<input v-model="name" type="text" placeholder="Örn. Adana Kebap" required/></label><label>Kategori<select v-model="category"><option v-for="item in categories" :key="item">{{item}}</option></select></label></div>
  <label>Fiyat *<div class="price-input"><input v-model.number="price" type="number" min="1" placeholder="250" required/><span>₺</span></div></label>
  <div class="modal-actions"><button type="button" class="cancel" @click="modal=false">Vazgeç</button><button class="primary" type="submit"><Check :size="17"/> {{editing?'Değişiklikleri kaydet':'Ürünü kaydet'}}</button></div>
</form></div>
</template>
<style scoped>
.inventory-page{max-width:1240px;margin:auto}.inventory-head{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:24px}.inventory-head h2{font-size:34px;letter-spacing:-1.2px;margin:5px 0 7px}.inventory-head p{font-size:13px;color:var(--muted);margin:0}.primary{height:44px;border:0;border-radius:11px;padding:0 19px;background:#202522;color:#fff;display:inline-flex;align-items:center;justify-content:center;gap:9px;font-weight:700;font-size:13px;cursor:pointer;box-shadow:0 8px 20px #20252229;transition:.2s}.primary:hover{background:var(--orange);transform:translateY(-1px)}
.head-actions{display:flex;gap:9px}.delete-all{height:44px;border:1px solid #efb9b3;border-radius:11px;padding:0 15px;background:#fff6f4;color:#d85146;display:flex;align-items:center;justify-content:center;gap:8px;font-size:12px;font-weight:700;cursor:pointer;transition:.2s}.delete-all:hover{background:#d85146;border-color:#d85146;color:#fff}.delete-all:disabled{opacity:.45;cursor:not-allowed}.delete-all:disabled:hover{background:#fff6f4;color:#d85146}
.summary{display:flex;align-items:center;gap:28px;background:#fff;border:1px solid var(--line);border-radius:14px;padding:16px 22px;margin-bottom:16px;box-shadow:0 4px 16px #2025220a}.summary div{display:flex;align-items:baseline;gap:10px}.summary span{color:var(--muted);font-size:12px}.summary strong{font-size:19px}.summary .green{color:#16a067}.summary>i{width:1px;height:24px;background:var(--line)}
.inventory-panel{background:#fff;border:1px solid var(--line);border-radius:16px;overflow:hidden;box-shadow:0 8px 30px #2025220e}.toolbar{display:flex;justify-content:space-between;align-items:center;padding:20px;border-bottom:1px solid var(--line)}.modern-search{width:min(390px,100%);box-shadow:none}.modern-search button{border:0;background:none;color:#999;display:grid;cursor:pointer}.result-count{font-size:11px;color:var(--muted);background:#f4f6f3;padding:7px 11px;border-radius:8px}.list-head,.product-row{display:grid;grid-template-columns:minmax(280px,1.8fr) minmax(100px,.55fr) minmax(120px,.65fr) minmax(210px,.8fr);align-items:center}.list-head{padding:11px 22px;background:#fafbfa;color:#929a95;font-size:10px;font-weight:700;letter-spacing:.8px;text-transform:uppercase}.product-row{min-height:92px;padding:14px 22px;border-top:1px solid #eef0ed;transition:.2s}.product-row:hover{background:#fffaf7}.product-main{display:flex;align-items:center;gap:14px;min-width:0}.product-main strong,.product-main small{display:block}.product-main small{color:#929a95;font-size:11px;margin-top:5px}.product-photo{width:62px;height:62px;border-radius:12px;overflow:hidden;display:grid;place-items:center;flex:none;background:#f1f3f0;color:#a8afa9}.product-photo img{width:100%;height:100%;object-fit:cover}.price{font-size:14px}
.switch-wrap{border:0;background:none;display:flex;align-items:center;gap:9px;color:#16895b;font-size:12px;font-weight:700;cursor:pointer}.switch{width:35px;height:20px;border-radius:20px;background:#18a96b;padding:3px}.switch i{display:block;width:14px;height:14px;border-radius:50%;background:#fff;transform:translateX(15px);box-shadow:0 1px 3px #0003;transition:.2s}.switch-wrap.off{color:#8c948f}.off .switch{background:#d4d9d5}.off .switch i{transform:none}.actions{display:flex;justify-content:flex-end;gap:7px}.actions button{height:36px;border-radius:9px;border:1px solid var(--line);background:#fff;display:flex;align-items:center;gap:7px;padding:0 11px;cursor:pointer;color:#626a65}.actions .edit:hover{border-color:var(--orange);color:var(--orange)}.actions .freeze:hover{color:#3777b9;background:#f0f7ff}.actions .delete{color:#d9564c}.actions .delete:hover{background:#fff2f0}.actions span{font-size:11px;font-weight:700}.empty-state{text-align:center;padding:70px 20px}.empty-state>span{width:58px;height:58px;background:#f1f3f0;color:#a4aca6;border-radius:16px;display:grid;place-items:center;margin:auto}.empty-state h3{font-size:16px;margin:15px 0 5px}.empty-state p{font-size:12px;color:var(--muted);margin:0}
.product-modal{width:min(100%,620px)}.modal-kicker{font-size:10px;letter-spacing:1.3px;color:var(--orange);font-weight:800}.product-picker{height:132px}.product-picker>div{display:flex;flex-direction:column;align-items:center;gap:5px}.product-picker strong{font-size:12px}.product-picker small{font-size:10px!important;margin:0!important}.product-picker img{width:100%;height:100%}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.product-modal select{width:100%;height:44px;border:1.5px solid var(--line);border-radius:12px;padding:0 13px;background:#fff}.price-input{position:relative}.price-input span{position:absolute;right:15px;top:50%;transform:translateY(-50%);font-weight:700;color:var(--muted)}.price-input input{padding-right:38px}.modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:28px}.modal-actions .primary{width:auto;margin:0}.cancel{height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;padding:0 18px;cursor:pointer;font-weight:600;color:#69716c}
@media(max-width:850px){.list-head{display:none}.product-row{grid-template-columns:1fr auto;gap:14px}.price{grid-column:2;grid-row:1}.switch-wrap{grid-column:1}.actions{grid-column:2}}@media(max-width:600px){.inventory-head{align-items:stretch;flex-direction:column}.head-actions{display:grid;grid-template-columns:1fr 1fr}.inventory-head .primary,.delete-all{width:100%}.summary{gap:14px;justify-content:space-between}.summary div{display:block}.summary strong{display:block}.product-row{padding:14px}.actions .edit span{display:none}.form-grid{grid-template-columns:1fr}.modal-actions{flex-direction:column-reverse}.modal-actions button{width:100%!important}}
</style>
